import { Inter } from 'next/font/google';
import * as React from 'react';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode,
}) {
  const ticker = 'pltr';
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
      <section>
          <nav>
            <Link href='/'>home</Link> | <Link href={`/analyze/${ticker}`}>Analysis</Link>
          </nav>
          {children}
        </section>
      </body>
    </html>
  )
}
